---
- hosts: server1
  become: true
  remote_user: admin
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: latest

    - name: Install tree
      apt:
        name: tree
        state: latest

    - name: Update apt cache and install necessary packages
      apt:
        update_cache: yes
        name:
          - openjdk-17-jdk
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    # - name: Add Docker GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker APT repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    #     state: present

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository
      ansible.builtin.shell: |
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install Docker
      apt:
        update_cache: yes
        name: docker-ce
        state: latest
