---
- hosts: server1
  become: true
  remote_user: admin
  tasks:
  - name: Update apt cache and install necessary packages
    apt:
      update_cache: yes
      name:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - git
        - tree
        - openjdk-17-jdk
        - lsb-release
      state: latest

  - name: Create directory for Docker GPG key
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker's official GPG key
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Add Docker repository to Apt sources
    ansible.builtin.shell: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update apt cache and install Docker
    apt:
      update_cache: yes
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest

  - name: Add user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes

  - name: Reset ssh connection to allow user changes to take effect
    meta: reset_connection

  - name: Open Docker TCP port in iptables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 2375
      jump: ACCEPT

  - name: Update Docker configuration
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
        }
      owner: root
      group: root
      mode: '0644'

  - name: Restart Docker
    systemd:
      name: docker
      state: restarted